// Generates and validates a per-company config (config/company.<id>.yaml) from CLI inputs,
// so onboarding a tenant needs no hand-edited YAML (plan 1bis §3, SPEC §0/§6).
//
// Usage:
//   npm run create-company -- --id acme --name "Acme Corp" \
//     --roles hr_admin,manager,employee \
//     --sheet <spreadsheetId> --folder <driveFolderId> --template <docTemplateId> \
//     [--modules hr.recruitment] [--out config/company.acme.yaml] [--force]
//
// The output is validated against companyConfigSchema (zod) before writing — a bad input
// fails here, not at server boot.
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { writeFileSync, existsSync } from "node:fs";
import { randomBytes } from "node:crypto";
import { stringify as toYaml } from "yaml";
import { companyConfigSchema } from "../src/core/config/schema.js";
import { hashApiKey } from "../src/core/auth/apiKey.js";

const __dirname = dirname(fileURLToPath(import.meta.url));

function arg(name: string): string | undefined {
  const i = process.argv.indexOf(`--${name}`);
  return i >= 0 ? process.argv[i + 1] : undefined;
}
const has = (name: string): boolean => process.argv.includes(`--${name}`);
const list = (v: string | undefined): string[] =>
  (v ?? "").split(",").map((s) => s.trim()).filter(Boolean);

const id = arg("id");
const name = arg("name");
if (!id || !name) {
  console.error('usage: create-company --id <id> --name "<name>" --roles a,b,c [--sheet ..] [--folder ..] [--template ..] [--modules ..] [--out ..] [--force]');
  process.exit(1);
}

const roles = list(arg("roles"));
const enabledModules = list(arg("modules"));

// Mint this company's API key: a random secret shown ONCE, of which only the sha256 hash is
// stored in the config. `--key <raw>` lets the operator supply a pre-agreed key instead.
const rawKey = arg("key") ?? `hris_${id}_${randomBytes(24).toString("base64url")}`;
const config = {
  company: {
    id,
    name,
    enabledModules: enabledModules.length ? enabledModules : ["hr.recruitment"],
    roles: roles.length ? roles : ["hr_admin", "manager", "employee"],
  },
  auth: { apiKeyHash: hashApiKey(rawKey) },
  resources: {
    googleDrive: { hrKnowledgeFolderId: arg("folder") ?? "" },
    googleSheets: { hrRecruitmentSheetId: arg("sheet") ?? "" },
    googleDocs: { jobDescriptionTemplateId: arg("template") ?? "" },
  },
};

const parsed = companyConfigSchema.safeParse(config);
if (!parsed.success) {
  console.error("invalid company config:", JSON.stringify(parsed.error.flatten(), null, 2));
  process.exit(1);
}

const outPath = arg("out") ?? join(__dirname, "..", "config", `company.${id}.yaml`);
if (existsSync(outPath) && !has("force")) {
  console.error(`refusing to overwrite existing file: ${outPath} (pass --force to replace)`);
  process.exit(1);
}

const header =
  "# Per-company wiring (SPEC §6). Generated by scripts/create-company.ts — validated by zod.\n" +
  "# Share the Sheet, Drive folder and Doc template with the service-account email (edit access).\n";
writeFileSync(outPath, header + toYaml(config));
console.log(`wrote ${outPath}`);
if (!arg("key")) {
  console.log("\n=== API KEY (shown once — store it securely, give it to this company) ===");
  console.log(`  x-api-key: ${rawKey}`);
  console.log("Only its sha256 hash is saved in the config; the raw key cannot be recovered.\n");
}
console.log("next: run setup-company-sheet to create the rec_jobDesc/Config tabs, then add the path to COMPANY_CONFIG_PATH.");
